# -*- coding: utf-8 -*-
"""election

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dzVlPt1r-otelHQjN9eNCUfwqUY3hiI0

<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>Colaboratory nedir?</h1>

Colaboratory &#40;ya da kısaca "Colab"&#41;, tarayıcınızda Python'u yazmanızı ve çalıştırmanızı sağlar. Üstelik: 
- Hiç yapılandırma gerektirmez
- GPU'lara ücretsiz erişim imkanı sunar
- Kolay paylaşım imkanı sunar

İster <strong>öğrenci</strong> ister <strong>veri bilimci</strong> ister <strong>yapay zeka araştırmacısı</strong> olun, Colab işinizi kolaylaştırabilir. Daha fazla bilgi edinmek için <a href="https://www.youtube.com/watch?v=inN8seMm7UI">Colab'e Giriş</a> videosunu izleyebilir ya da aşağıdan hemen kullanmaya başlayabilirsiniz.
"""

from flask import Flask, jsonify, abort, make_response, request, url_for,session
from flask import render_template, redirect
import json
import re
import requests 
import hashlib
import os
from web3 import Web3

rpc = "https://naklecha.blockchain.azure.com:3200/C7sLbEihlinGLsD2k9AXwVWH"

web3 = Web3(Web3.HTTPProvider(rpc))
abi = '[{"constant":true,"inputs":[],"name":"candidatesCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x2d35a8a2"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"candidates","outputs":[{"name":"id","type":"uint256"},{"name":"name","type":"string"},{"name":"voteCount","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x3477ee2e"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"voters","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function","signature":"0xa3ec138d"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor","signature":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_candidateId","type":"uint256"}],"name":"votedEvent","type":"event","signature":"0xfff3c900d938d21d0990d786e819f29b8d05c1ef587b462b939609625b684b16"},{"constant":false,"inputs":[],"name":"end","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0xefbe1c1c"},{"constant":false,"inputs":[{"name":"_candidateId","type":"uint256"}],"name":"vote","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0x0121b93f"}]'
contract_addr = "0xD6B1DbD429f998Dd09f36Cb246bE31b82b7a206C"


app = Flask(__name__)
app.secret_key = 'bende cikolata severim'

accounts = [ 
    '0xB0BE5EFDe83490f0d8fC64120461660098AE7599',
    '0xe0e577218063fc8648A4b04fDcFe2fD02990f734',
    '0xA55a74F93a50529f6F85658C22538eD9035551c3',
    '0x0b918ccbA35F62d80530F0223e0eA0DaB0C879BA',
    '0xCfc9EA020080496D2162B6EE8BFC84B5fbDF1FB5',
    '0xd84A6127e81Eb9384eB30b6A2D54E29A91798651',
    '0x35A3c8A48fb58B1d418D62c752Eeb4DA36128564',
    '0x50EC809051d823D0F979a1a974Ad63568bf7BEC1',
    '0x56Df378eF6AEB25Ec4fa22eDdB8f88B8407C2334',
    '0xa5cc1434694afA6daB030EEa5D6e4235e405643E' 
]

privatekeys = [
    '25d9479cd21fb800522f8e0c74513f0730f7afac9f3ac7a23d8ad69b7103be52',
    '01519292e7b9fb0d98149b7b202cbd2b99d92857804140fe927855cc26026a9d',
    '34f4f6e8a79cb192b957965b7764eb949f588027aee590557160bd2eca64123c',
    'cc85e4484592eadf0681fe9f2d6297c1cf4cb81321fe9454b43ad04bedcab87a',
    '4997b54bc7b835335f4324ef4e9f27fc78e42068799c07dba7f2ee517e995808',
    '448f522922fcfd184712c8b7e8bb82de255c6ca6aa8dda76d1e7aa4bdb819d49',
    '571f96e9291b198b7e024ab950d5868dbdc6b6137ee30bddb51ff450fa7591ce',
    '1e4acf03770503c9e5487fab22bb81484968a50b293d6bf528eb9e0fd5bd542e',
    '7c7aacbc4b3c839e0e870d6c08f63e3816c0b1384aa1dc6d05e9de95f2589106',
    '58f129cbace24078382559c366c6427f88179d35f2fac2ccdf62591e7e59cbac'
]

vote_tx = []
voted = []
ended = 0

@app.route("/" , methods=['POST'])
def home():
    if(not ended):
        try:
            data = eval(request.data) # {"aadhaarID":int(),"candidateID":int()}
            aid = int(data["aadhaarID"])-1
            if(aid in voted):
                return "Daha önce oy verildi.",400
            cid = int(data["candidateID"])
            acc = accounts[aid]
            pvt = privatekeys[aid]
            contract = web3.eth.contract(address=contract_addr, abi=abi)
            transaction  = contract.functions.vote(cid).buildTransaction()
            transaction['nonce'] = web3.eth.getTransactionCount(acc)

            signed_tx = web3.eth.account.signTransaction(transaction, pvt)
            tx_hash = web3.eth.sendRawTransaction(signed_tx.rawTransaction)
            vote_tx.append(tx_hash)
            voted.append(aid)
            return "Oy başarıyla kullanıldı.",200
        except:
            return "İşlem sırasında hata oluştu.",500
    else:
        return "Seçim dönemi sona erdi.",400

@app.route("/results" , methods=['GET'])
def count():
    if(ended):
            res = []
            election = web3.eth.contract(address=contract_addr, abi=abi)
            for i in range(election.caller().candidatesCount()):    
                res.append(election.caller().candidates(i+1))
            return json.dumps(res),200
    else:
        return "Seçim hala devam ediyor..",400

@app.route("/end" , methods=['POST'])
def end_election():
    global ended
    ended += 1
    acc = '0xB0BE5EFDe83490f0d8fC64120461660098AE7599'
    pvt = '25d9479cd21fb800522f8e0c74513f0730f7afac9f3ac7a23d8ad69b7103be52'
    contract = web3.eth.contract(address=contract_addr, abi=abi)
    transaction  = contract.functions.end().buildTransaction()
    transaction['nonce'] = web3.eth.getTransactionCount(acc)

    signed_tx = web3.eth.account.signTransaction(transaction, pvt)
    tx_hash = web3.eth.sendRawTransaction(signed_tx.rawTransaction)
    return "Seçim başarıyla sona erdi.\nTx Hash : %s"%(str(tx_hash)),200

@app.route("/number_of_users" , methods=['GET'])
def number_of_users(): 
    try:
        return str(len(accounts)),200
    except:
        return "Hata işleme..",500

@app.route("/isended" , methods=['GET'])
def isended(): 
    return str(ended>0),200

@app.route("/candidates_list" , methods=['GET'])
def candidates_list():
    try:
        res = []
        election = web3.eth.contract(address=contract_addr, abi=abi)
        for i in range(election.caller().candidatesCount()):    
            res.append(election.caller().candidates(i+1)[1]) #name
        return json.dumps(res),200
    except:
        return "Hata işleme..",500

if __name__ == '__main__':
	app.run(host="0.0.0.0" ,port=80, debug = True)

"""## <strong>Başlarken</strong>

Okuduğunuz doküman statik bir web sayfası değil, kod yazmanıza ve yürütmenize imkan veren <strong>Colab not defteri</strong> adında etkileşimli bir ortamdır.

Örneğin, buradaki <strong>kod hücresinde</strong>, bir değeri hesaplayan, bir değişken içinde saklayan ve sonucu yazdıran kısa bir Python dizesi görebilirsiniz:
"""

seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

"""Yukarıdaki hücrede kodu yürütmek için tıklayarak seçin, ardından ya kodun sol tarafındaki oynat düğmesine basın ya da "Command/Ctrl+Enter" klavye kısayolunu kullanın. Kodu düzenlemek için hücreyi tıklamanız yeterlidir. Sonrasında düzenlemeye başlayabilirsiniz.

Bir hücrede tanımladığınız değişkenler daha sonra başka hücrelerde kullanılabilir:
"""

seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

"""Colab not defterleri; <strong>yürütülebilir kod</strong>, <strong>zengin metin</strong>, <strong>resimler</strong>, <strong>HTML</strong>, <strong>LaTeX</strong> ve diğer öğeleri tek bir dokümanda birleştirmenizi sağlar. Oluşturduğunuz Colab not defterleri Google Drive hesabınızda saklanır. Colab not defterlerinizi arkadaşlarınızla veya iş arkadaşlarınızla kolayca paylaşabilir, not defterlerinize yorum yapmalarını, hatta düzenlemelerini sağlayabilirsiniz. Daha fazla bilgiyi <a href="/notebooks/basic_features_overview.ipynb">Colab'e Genel Bakış</a> bölümünde bulabilirsiniz. Yeni bir Colab not defteri oluşturmak için yukarıdaki Dosya menüsünü ya da <a href="http://colab.research.google.com#create=true">yeni bir Colab not defteri oluşturma</a> bağlantısını kullanabilirsiniz.

Colab not defterleri, Colab tarafından barındırılan Jupyter not defterleridir. Jupyter projesi hakkında daha fazla bilgiyi <a href="https://www.jupyter.org">jupyter.org</a> adresinde bulabilirsiniz.

## Veri bilimi

Colab ile popüler Python kitaplıklarının tüm avantajlarından yararlanarak veri analiz edip görselleştirebilirsiniz. Aşağıdaki kod hücresi rastgele veri oluşturmak için <strong>numpy</strong>'yi, bu veriyi görselleştirmek için de <strong>matplotlib</strong>'i kullanır. Kodu düzenlemek için hücreyi tıklamanız yeterlidir. Sonrasında düzenlemeye başlayabilirsiniz.
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Sample Visualization")
plt.show()

"""Kendi verilerinizi Google Drive hesabınızdan &#40;e-tablolar dahil&#41;, GitHub'dan ve diğer pek çok kaynaktan Colab not defterlerine aktarabilirsiniz. Veri içe aktarma ve Colab'in veri bilimi için nasıl kullanılabileceği hakkında daha fazla bilgi edinmek için <a href="#working-with-data">Verilerle Çalışma</a> bölümünün altındaki bağlantılara bakabilirsiniz.

## Makine öğrenimi

Colab ile bir resim veri kümesini içe aktarabilir, üzerinde bir resim sınıflandırıcıyı eğitebilir ve modeli değerlendirebilirsiniz. Hem de sadece <a href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb">birkaç satır kodla</a>. Colab not defterleri Google'ın bulut sunucularında kod yürütür. Yani makinenizin gücünden bağımsız olarak, <a href="#using-accelerated-hardware">GPU'lar ve TPU'lar</a> dahil Google donanımının gücünden yararlanabilirsiniz. Tek ihtiyacınız olan şey bir tarayıcıdır.

Colab, makine öğrenimi topluluğunda yaygın olarak şu uygulamalarla kullanılır:
- TensorFlow'u kullanmaya başlama
- Nöral ağ geliştirme ve eğitme
- TPU'lar ile deneme yapma
- Yapay zeka araştırmalarını yayma
- Eğitici oluşturma

Makine öğrenimi uygulamalarını açıklayarak tanıtan örnek Colab not defterlerini görmek için aşağıdaki <a href="#machine-learning-examples">makine öğrenimi örneklerine</a> bakabilirsiniz.

## Diğer Kaynaklar

### Colab'de Not Defterleriyle Çalışma
- [Colaboratory'ye Genel Bakış](/notebooks/basic_features_overview.ipynb)
- [Markdown rehberi](/notebooks/markdown_guide.ipynb)
- [Kitaplıkları içe aktarma ve bağımlıları yükleme](/notebooks/snippets/importing_libraries.ipynb)
- [GitHub'da not defteri kaydetme ve yükleme](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)
- [Etkileşimli formlar](/notebooks/forms.ipynb)
- [Etkileşimli widget'lar](/notebooks/widgets.ipynb)
- <img src="/img/new.png" height="20px" align="left" hspace="4px" alt="New"></img>
 [Colab'de TensorFlow 2](/notebooks/tensorflow_version.ipynb)

<a name="working-with-data"></a>
### Verilerle Çalışma
- [Veri yükleme: Drive, E-Tablolar ve Google Cloud Storage](/notebooks/io.ipynb) 
- [Grafikler: Veri görselleştirme](/notebooks/charts.ipynb)
- [BigQuery'yi kullanmaya başlama](/notebooks/bigquery.ipynb)

### Makine Öğrenimi Hızlandırılmış Kursu
Google'ın online Makine Öğrenimi kursundan birkaç not defterini burada bulabilirsiniz. Daha fazlası için <a href="https://developers.google.com/machine-learning/crash-course/">tam kurs web sitesine</a> bakın.
- [Pandas'a giriş](/notebooks/mlcc/intro_to_pandas.ipynb)
- [TensorFlow kavramları](/notebooks/mlcc/tensorflow_programming_concepts.ipynb)
- [TensorFlow ile ilk adımlar](/notebooks/mlcc/first_steps_with_tensor_flow.ipynb)
- [Nöral ağlara giriş](/notebooks/mlcc/intro_to_neural_nets.ipynb)
- [Seyrek veriler ve yerleştirilmiş öğelere giriş](/notebooks/mlcc/intro_to_sparse_data_and_embeddings.ipynb)

<a name="using-accelerated-hardware"></a>
### Hızlandırılmış Donanım Kullanma
- [GPU'lar ile TensorFlow](/notebooks/gpu.ipynb)
- [TPU'lar ile TensorFlow](/notebooks/tpu.ipynb)

<a name="machine-learning-examples"></a>

## Makine Öğrenimi Örnekleri

Colaboratory'nin mümkün kıldığı etkileşimli makine öğrenimi analizlerinin uçtan uca örneklerini görmek için, <a href="https://tfhub.dev">TensorFlow Hub</a>'daki modelleri kullanan bu eğiticilere bakın.

Öne çıkan birkaç örnek:

- <a href="https://tensorflow.org/hub/tutorials/tf2_image_retraining">Bir Resim Sınıflandırıcıyı Yeniden Eğitme</a>: Çiçekleri ayırt etmek için önceden eğitilmiş bir resim sınıflandırıcının üzerine bir Keras modeli inşa eder.
- <a href="https://tensorflow.org/hub/tutorials/tf2_text_classification">Metin Sınıflandırma</a>: IMDB'deki film yorumlarını <em>olumlu</em> veya <em>olumsuz</em> olarak sınıflandırır.
- <a href="https://tensorflow.org/hub/tutorials/tf2_arbitrary_image_stylization">Stil Aktarımı</a>: Resimler arasında stil aktarımı yapmak için derin öğrenmeyi kullanır.
- <a href="https://tensorflow.org/hub/tutorials/retrieval_with_tf_hub_universal_encoder_qa">Çok Dilli Evrensel Cümle Kodlayıcı Soru-Cevap</a>: SQuAD veri kümesinden soruları cevaplamak için bir makine öğrenimi modeli kullanır.
- <a href="https://tensorflow.org/hub/tutorials/tweening_conv3d">Video İnterpolasyonu</a>: Bir videonun ilk ve son karesi arasında ne olduğunu tahmin eder.
"""